### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jserot** [janestreet/hardcaml#4]
Is there any written documentation on this package, esp. 
- syntax of the DSL
- how to use the tools
- ...
?
The only information I was able to find was from A. Ray's talk ("OCaml  All the Way Down"). Very, very interesting. 
Also, are the demo code used in this talk available s/w ?

**Comment by andrewray** [comment]
We have pushed this to top of stack and documentation should start to appear in the repository shortly.  It'll take us a few weeks to tidy it up properly.

Regarding the code for the talk - it's horribly bit-rotted at this point.  I could probably get the hardware design out but I think the more interesting part of that was the OCaml integration - and it's really tough to figure out how to release that set of hacks cleanly (its effectively a small cross-compiled system, and opam does not really support that).

**Comment by andrewray** [comment]
We released the docs a few weeks ago.

Happy for any feedback to improve them!
